### ISSUE TITLE
No project match

### ISSUE THREAD

**Issue by artemkolotilkin** [bchatard/jetbrains-alfred-workflow#10]
Q | A
--- | ---
Workflow version | v1.0.9
OSX Version | 10.12.1
Alfred Version | 3
JetBrains Product/Version | PhpStorm / 2016.3
Installation type | classic .dmg

### Description
I'm trying to use this workflow (thanks for it, by the way), but it doesn't find any projects. I tried to debug it and got to this step:
`xmllint --xpath '//component[@name="RecentDirectoryProjectsManager"]/option[@name="recentPaths"]/list/option/@value' ~/Library/Preferences/PhpStorm2016.3/options/recentProjectDirectories.xml`

which returns this:
`value="$USER_HOME$/Sites/microsites.dev" value="$USER_HOME$/Sites/example.dev"`

Is it the right output? It feels like it should return just a value, without the attribute name.

I also couldn't get debug to work. AddDebug doesn't output anything for me.

Thanks in advance for looking into that.

**Comment by bchatard** [comment]
Hi @artemkolotilkin,

Thanks :-)

Now for your problem, I need your help. I'm still on Yosemite so I can't test for now.

The return value with `$USER_HOME$` came from Jetbrains XML, so it's ok.

Can you enable debug mode?
1. Go to workflow view
2. Double-click on `pstorm` Script filter
3. And then click on "open folder" icon
![image](https://cloud.githubusercontent.com/assets/829364/20758053/798435f4-b710-11e6-8ae0-fe048e478e77.png)

4. Edit `main.zsh`, and change `DEBUG=0` to `DEBUG=1` (line 15)

5. And then hit you hotkey and search for a project.

A log file will be generated in this folder. Can you provide it? (remove personal data before if needed)

**Comment by artemkolotilkin** [comment]
Enabled Debug code helped a lot :-)

Here is an excerpt from the log file:
Projects Path:
```
/Users/artem/Sites/example.dev

Process /Users/artem/Sites/example.dev
Project Name 
```

It looks like Project Name is not populated by `extractProjectName()` function.

**Comment by artemkolotilkin** [comment]
Ok, I see where the problem is. Looks like it doesn't like special characters in the path. I had "&" in a path and because of that those projects were not listed. I've added another project without special characters and it's working fine now.

**Comment by bchatard** [comment]
ok, thanks for the feedback. 
I will try to find a workaround for "special chars".

**Comment by bchatard** [comment]
@artemkolotilkin can you test version [1.0.10](https://github.com/bchatard/jetbrains-alfred-workflow/tree/v1.0.10) ?

**Comment by shallwefootball** [comment]
"no project match"

not listed project in webstorm 2016.3 in macOS.

**Comment by bchatard** [comment]
@shallwefootball can you try to add log (cf. https://github.com/bchatard/jetbrains-alfred-workflow/issues/10#issuecomment-263901026), and let me now

**Comment by shallwefootball** [comment]
see my case.

![mycase](https://cloud.githubusercontent.com/assets/9348198/22973660/f35b3042-f3c1-11e6-8fcb-78b8f5249f4a.gif)

**Comment by bchatard** [comment]
@shallwefootball please provide log file (in the directory with `main.zsh`) or maybe try to re-download package (it was outdated - #14 )

**Comment by shallwefootball** [comment]
@bchatard i re-downloaded it and it was executed. thank you 👍

**Comment by generalic** [comment]
No project match for PyCharm, I have two projects there: recipes-database and test_project.
Version: PyCharm 2017.2.1 Build #PY-172.3544.46
Here is log file:


			AppPath: /Applications/PyCharm.app

			Config Path: /Users/generalic/Library/Preferences/PyCharm2017.2
			Work with: /Users/generalic/Library/Preferences/PyCharm2017.2/options/recentProjectDirectories.xml
			Raw Projects Path:
			 value="$USER_HOME$/projects/reciepes-database" value="$USER_HOME$/projects/PycharmProjects/test_project"
			Projects Path:
			/Users/generalic/projects/reciepes-database
			/Users/generalic/projects/PycharmProjects/test_project
				Process /Users/generalic/projects/reciepes-database
			extractProjectName via workspace.xml
			extractProjectName via workspace.xml - alternative
				 Project Name 

				Process /Users/generalic/projects/PycharmProjects/test_project
				 Project Name

**Comment by bchatard** [comment]
@generalic please open an other issue (and add your workspace.xml), thanks
