### ISSUE TITLE
我的软件版本更新了，请问具体该怎么update the Command-line launcher 

### ISSUE THREAD

**Issue by ChlZhYa** [bchatard/jetbrains-alfred-workflow#17]

**Comment by bchatard** [comment]
Hi @Zhangchangle,

not really sure about the Google Translate translation.

You reference this problem https://github.com/bchatard/jetbrains-alfred-workflow#known-issue
So you need to follow this steps again after each update https://github.com/bchatard/jetbrains-alfred-workflow#requirements

**Comment by vivaxy** [comment]
@bchatard Translation:
Q: How to update the Command-line launcher after the update of my software?

I think the answer is: Create Command-line Launcher again.

@Zhangchangle 再创建一次命令行工具就行了

**Comment by bchatard** [comment]
@vivaxy thanks :-)
