### ISSUE TITLE
Support for JetBrains rider?

### ISSUE THREAD

**Issue by voydz** [bchatard/jetbrains-alfred-workflow#18]
Q | A
--- | ---
Workflow version | _1.0.12_
OSX Version | _10.12.04_
Alfred Version | _3_
JetBrains Product/Version | _Rider EAP 21_
Installation type | _JB Toolbox_

### Description
Hey there,

first of all thanks for this awesome workflow, already using it a lot. 

This is just a little feature request to include Rider, JB's "new" C# IDE. Already tried to add it in the workflow, but it seems the `main.zsh` script does not support it out of the box.

greetings,
voydz

**Comment by bchatard** [comment]
Hi @voydz 

Thanks :-)
I will work on it quickly

**Comment by bchatard** [comment]
working on it

Rider configuration is not the same as other JetBrains product

**Comment by voydz** [comment]
@bchatard Thats what I thought :/

Let me know, if I can help you in any way. :)

**Comment by bchatard** [comment]
@voydz 

can you send me this file : `~/Library/Preferences/Rider10/options/recentSolutions.xml` (remove sensible data if needed)

**Comment by voydz** [comment]
@bchatard No problem.

Have a look at this gist https://gist.github.com/voydz/c5dc3673bab8cacc91c2f4e8081aaf0f

**Comment by bchatard** [comment]
@voydz sorry busy at work...

Can you try version available in PR #20 ?

**Comment by voydz** [comment]
hey @bchatard,

thanks for your effort, seems to work fine for me. :)

**Comment by bchatard** [comment]
closed by #20
