### ISSUE TITLE
Maybe cache project results?

### ISSUE THREAD

**Issue by voydz** [bchatard/jetbrains-alfred-workflow#19]
Q | A
--- | ---
Workflow version | _1.0.12_
OSX Version | _10.12.04_
Alfred Version | _3_
JetBrains Product/Version | _Rider EAP 21_
Installation type | _JB Toolbox_

### Description
Again, a feature idea and not really an issue. I thought it would be quite nice "quality of life" feature, if project results would be cached after a scan somehow. 

The benefit would be to get instant results on subsequent searches. (Of course, the search and "recache" could run in the background and update the results if finished.)

**Comment by bchatard** [comment]
@voydz thanks for the proposal

I'm working on some rework, I will try to add this

**Comment by voydz** [comment]
@bchatard Thanks, this sounds awesome!

**Comment by bchatard** [comment]
@voydz I push a v2 version today. It's a full rewrite in PHP, for me it's quicker than v1.
Don't worry I will work on cache system too :-)

**Comment by voydz** [comment]
@bchatard nice! Thanks for the update. I will try it out immediately. Much appreciated, thanks again. :)

**Comment by voydz** [comment]
@bchatard so I gave version `2.0.0-beta` a test run the last few days. I have to say, that the performance improvements are really awesome. No flaws detected so far. Keep up the good work!

**Comment by bchatard** [comment]
@voydz finally ! I add a basic cache management, you can give a try in [beta4 branch](https://github.com/bchatard/jetbrains-alfred-workflow/tree/v.2.0.0-beta4)

**Comment by voydz** [comment]
@bchatard Hi, thanks for your update. Just testet beta4 and I have to say that the performance improvements are really noticeable once more. Thanks again! 👍

**Comment by bchatard** [comment]
#31 merged
