### ISSUE TITLE
having problem finding project

### ISSUE THREAD

**Issue by kartolo** [bchatard/jetbrains-alfred-workflow#2]
Hi,

I'm trying to debug the zsh script, but I am not really good at shell scripting. I can only find that the getProjectsPath returns values with "n" between every project paths. this is wrong, doesn't it?

best regards.

**Comment by bchatard** [comment]
Hi,

I use "\n" as value separator between project paths.

Could you please give me more detail about your issue?
- Zsh version (`/bin/zsh --version`) 
- Which Jetbrains product and version

Thanks,

**Comment by kartolo** [comment]
zsh version => zsh 5.0.5 (x86_64-apple-darwin14.0)
I'm using PHPStorm 10.0.1. Your old Workflow works for workspaces created with old PHPStorm. I just updated my PHPStorm to 10 yesterday and the old workflow doesn't find the newly created workspace.

**Comment by bchatard** [comment]
Can you re-generate the CLI Launcher?
In PhpStorm: Tools > Create Command-Line Launcher

**Comment by kartolo** [comment]
remove the old CLI and recreated it, not helping :(

**Comment by bchatard** [comment]
Can you provide to me debug information about this workflow:
Open Alfred preferences, go to _Workflows_ and select _Jetbrains - Open Project_. Then click on the little bug (top right corner), a console appear. In this console, set _Log_ to _All information_. And start a search with Alfred. The console will display any information, that you could post here.

**Comment by kartolo** [comment]
```
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items>
<item uid="none" valid="yes" autocomplete=""><title>No project match &apos;&apos;</title><subtitle>No project match &apos;&apos;</subtitle><arg></arg><icon type="fileicon">/Applications/PhpStorm.app</icon></item> </items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items>
<item uid="none" valid="yes" autocomplete="w"><title>No project match &apos;w&apos;</title><subtitle>No project match &apos;w&apos;</subtitle><arg></arg><icon type="fileicon">/Applications/PhpStorm.app</icon></item> </items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items>
<item uid="none" valid="yes" autocomplete="ww"><title>No project match &apos;ww&apos;</title><subtitle>No project match &apos;ww&apos;</subtitle><arg></arg><icon type="fileicon">/Applications/PhpStorm.app</icon></item> </items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items>
<item uid="none" valid="yes" autocomplete="www"><title>No project match &apos;www&apos;</title><subtitle>No project match &apos;www&apos;</subtitle><arg></arg><icon type="fileicon">/Applications/PhpStorm.app</icon></item> </items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items>
<item uid="none" valid="yes" autocomplete="www_"><title>No project match &apos;www_&apos;</title><subtitle>No project match &apos;www_&apos;</subtitle><arg></arg><icon type="fileicon">/Applications/PhpStorm.app</icon></item> </items>
```

**Comment by bchatard** [comment]
Sorry, I don't see what's wrong :-( 
Can you try this debug version
[JetBrains - Open project - Issue2.alfredworkflow.zip](https://github.com/bchatard/jetbrains-alfred-workflow/files/52163/JetBrains.-.Open.project.-.Issue2.alfredworkflow.zip)

**Comment by kartolo** [comment]
following paths are shown in the debug. Interesting is, that "n" was added at the end of the project's name

```
/Users/kartolo/workspace/project1n/Users/kartolo/workspace/project2n/Users/kartolo/project3n
```

PS: I changed the project name with project1-3 :)

**Comment by bchatard** [comment]
It's weird… It's `\n` normally…
I will take a look on this quickly

Can you provide your `sed` version and path? (`sed --version` & `which sed`)

thanks,

**Comment by bchatard** [comment]
can you try the new version (just released) and let me know if it is better?

thanks,

**Comment by kartolo** [comment]
still doesn't work :(

```
○ → which sed
/usr/bin/sed
```

sed -v or --version or -V don't work :(

I'm on OSX Yosemite 10.10.5 (it's work's Macbook, can't update to El Capitan yet).
I'll try installing sed from brew

**Comment by kartolo** [comment]
installing gnu-sed from brew works.

```
brew install gnu-sed --with-default-names
```

without `--with-default-names` I need to change all `sed` with `gsed`

**Comment by bchatard** [comment]
thanks for the feedback. I also use sed from brew
I need to find a fix for "OSX sed"

**Comment by bchatard** [comment]
@kartolo I release a version with bug fix for native `sed` command. It will solved this issue. 
Let me know if it's ok for you

**Comment by kartolo** [comment]
@bchatard it works. just uninstalled brew gnu-sed and installed 0.5. Works perfect :+1:
