### ISSUE TITLE
can't get project name from new workspace.xml

### ISSUE THREAD

**Issue by dark-lbp** [bchatard/jetbrains-alfred-workflow#22]
Q | A
--- | ---
Workflow version | _1.0.13_
OSX Version | _10.12.6_
Alfred Version | _3_
JetBrains Product/Version | _PyCharm CE / 2017.2_
Installation type | _classic .dmg_

### Description
Workflow can't get project name from new workspace.xml. I enable the debug output and get some message.
```
# This is new version workspace.xml
	Process /Users/XXX/mywork_space/Projects/Fuzzing/kitty
extractProjectName via workspace.xml
	 Project Name

# This is the old version workspace.xml
Process /Users/XXX/mywork_space/Projects/checkio
extractProjectName via workspace.xml
	 Project Name checkio
```
There is my workspace file.

[checkio_workspace.xml.txt](https://github.com/bchatard/jetbrains-alfred-workflow/files/1213836/checkio_workspace.xml.txt)
[kitty_workspace.xml.txt](https://github.com/bchatard/jetbrains-alfred-workflow/files/1213837/kitty_workspace.xml.txt)

**Comment by bchatard** [comment]
Ok the XML structure change, I will add a workaround asap

thanks for the feedback

**Comment by bchatard** [comment]
@dark-lbp can you try version available in PR #23

**Comment by dark-lbp** [comment]
@bchatard I tried PR #23, it's work. I can get all project name now. thanks!

**Comment by bchatard** [comment]
ok, thanks again
