### ISSUE TITLE
charm - no project match

### ISSUE THREAD

**Issue by generalic** [bchatard/jetbrains-alfred-workflow#24]
Q | A
--- | ---
Workflow version | v1.0.14
OSX Version | 10.12.6
Alfred Version |  3
JetBrains Product/Version | PyCharm / 2017.2.1
Installation type | classic .dmg

### Description

No project match for PyCharm, I have two projects there: recipes-database and test_project.
Version: PyCharm 2017.2.1 Build #PY-172.3544.46
Here is log file:

			AppPath: /Applications/PyCharm.app

			Config Path: /Users/generalic/Library/Preferences/PyCharm2017.2
			Work with: /Users/generalic/Library/Preferences/PyCharm2017.2/options/recentProjectDirectories.xml
			Raw Projects Path:
			 value="$USER_HOME$/projects/reciepes-database" value="$USER_HOME$/projects/PycharmProjects/test_project"
			Projects Path:
			/Users/generalic/projects/reciepes-database
			/Users/generalic/projects/PycharmProjects/test_project
				Process /Users/generalic/projects/reciepes-database
			extractProjectName via workspace.xml
			extractProjectName via workspace.xml - alternative
				 Project Name 

				Process /Users/generalic/projects/PycharmProjects/test_project
				 Project Name 

### Step to reproduce
...

**Comment by generalic** [comment]
@bchatard you mentioned to add workspace.xml, where should I find it?
EDIT: for specific project or global one?

**Comment by generalic** [comment]
OK I've deleted .idea folder inside specific project, then reopened project and now it works.
Issue was that I copied project folder from one to other machine and it contained old .idea folder(from older PyCharm version).

**Comment by bchatard** [comment]
thanks for feedback

FYI, workspace.xml is located under `.idea` directory
