### ISSUE TITLE
android-studio studio filter only list two projects, not all of them

### ISSUE THREAD

**Issue by GabLeRoux** [bchatard/jetbrains-alfred-workflow#25]
Q | A
--- | ---
Workflow version | _2.0.0-beta1_
OSX Version | _10.12.6 (16G29)_
Alfred Version | _v3.5 [876]_
JetBrains Product/Version | _Android Studio 2.3.3_
Installation type | _classic .dmg_

### Description

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1264761/30913530-8f1eaa6c-a35e-11e7-8ffa-57dc88d29d72.png">

<img width="673" alt="image" src="https://user-images.githubusercontent.com/1264761/30913813-7d63fb8c-a35f-11e7-9c80-d02a31f08dd0.png">

`studio` doesn't seem to find all of my projects. The two shown projects are always the same ones.

I currently have 3 projects in android-studio, but the plugin only shows two of them. I friend did the same and also has the problem, he has ~9 projects and the plugin only show two of them.

### Step to reproduce

1. Create more than two android projects
2. Install the alfred package
3. Write `studio ` and see only two projects

**Comment by bchatard** [comment]
Hi @GabLeRoux 

Question about Android projects, the file `app/src/main/res/values/strings.xml` is always present?
I want to use this value, but I don't know if it's "safe" for all projects: `<string name="app_name">My First Application</string>`

**Comment by GabLeRoux** [comment]
Good question 👍  
I took a look at the project that wasn't showing up and I confirm it's there. I can't say it's _always_ there, but it sounds like it's at least there by default. Generated at project creation based on values filled in.

```bash
cat app/src/main/res/values/strings.xml | grep app_name
```
```xml
    <string name="app_name">Café Jeunesse</string>
```

A good test for this could be to try to build a project with the line removed. If we can submit an app without this, chances are some people may have removed it. But it may be a dark edge case that may be ignored. 🍻

**Comment by bchatard** [comment]
Hi,

Can you give a try to new release in this branch: https://github.com/bchatard/jetbrains-alfred-workflow/tree/v2.0.0-beta2

Thanks,

**Comment by GabLeRoux** [comment]
I confirm it works for me, nice job! :D

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1264761/31138594-07d3e2e6-a83d-11e7-8da6-7c11c640d5b2.png">

🎉 

Edit: Teammate says it still fails for him. I asked him to add more details here. I commented here: https://github.com/bchatard/jetbrains-alfred-workflow/pull/26/files#r142475893

**Comment by bchatard** [comment]
Hi @GabLeRoux ,

I just push on new fix (same branch), can you give a try?

**Comment by GabLeRoux** [comment]
Still works for me with this version. I'll have my teammate give a try too 👍

**Comment by GabLeRoux** [comment]
Teammate tried and it seems to work fine now, you rock 🤘
