### ISSUE TITLE
Workflow does not find rider projects

### ISSUE THREAD

**Issue by voydz** [bchatard/jetbrains-alfred-workflow#32]
Q | A
--- | ---
Workflow version | _2.0.0-beta4_
OSX Version | _10.13.1_
Alfred Version | _3_
JetBrains Product/Version | _Rider / 2017.2_
Installation type | _JB Toolbox_

### Description
The workflow is not able to find rider projects.

![](https://i.imgur.com/tXvzO49.png)

### Step to reproduce

1. Follow installation steps for this workflow with rider 2017.2
2. Search for rider projects

**Comment by bchatard** [comment]
@voydz fixed, sorry. You need to [clean cache](https://github.com/bchatard/jetbrains-alfred-workflow#clean-projects-cache)
