### ISSUE TITLE
won't work if project name has spaces

### ISSUE THREAD

**Issue by rockkoca** [bchatard/jetbrains-alfred-workflow#38]
Q | A
--- | ---
Workflow version | _2.0.0_
OSX Version | _10.10.5 / 10.11.05_
Alfred Version | _3_
JetBrains Product/Version | _PhpStorm / 2016.1.1_
Installation type | _classic .dmg / Caskroom / JB Toolbox_

### Description
...
won't work if project name has spaces
### Step to reproduce
...
won't work if project name has spaces,

$(${BIN} ${QUERY//\\\\/})

Above changes can resolve the problem.

**Comment by bchatard** [comment]
Hi @rockkoca, 

It's on v1 on this workflow? Which version exactly?

Can you provide more details about the bug and your fix, please?

Thanks,
