### ISSUE TITLE
Feature request: add DataGrip support

### ISSUE THREAD

**Issue by remarkov** [bchatard/jetbrains-alfred-workflow#39]
Q | A
--- | ---
Workflow version | _2.0.0-beta6_
OSX Version | _10.12.6_
Alfred Version | _3.5.1_
JetBrains Product/Version | _DataGrip / 2017.2.3_
Installation type | _JB Toolbox_

### Description
Currently there is no support for JetBrains DataGrip so I think it would be nice to add it to this wonderful workflow. Thanks in advance!

**Comment by bchatard** [comment]
Hi @remarkov,

Nice DataGrip has a CLI now, I will add this quickly

**Comment by bchatard** [comment]
@remarkov can you check the new beta in #41?

**Comment by remarkov** [comment]
@bchatard wow! superfast! works perfectly! thank you so much!

**Comment by remarkov** [comment]
Hi @bchatard!
I'm afraid I was too quick to confirm that everything is working properly. After the DataGrip got updated by the Toolbox the Workflow still opens it in the old version of DataGrip. I can do more tests and provide any further info if required.

**Comment by bchatard** [comment]
Hi @remarkov,

It's "normal", you need to upgrade your comme line launcher : https://github.com/bchatard/jetbrains-alfred-workflow#how-to-update-the-command-line-launcher-after-the-update-of-my-software

**Comment by remarkov** [comment]
Indeed, that helped, thanks! I also had to run `jb`to clean the cache so it will show the proper project path in the "subtext". Cheers!

**Comment by bchatard** [comment]
I need to update the doc to be more clear about this case, thanks for your feedback
