### ISSUE TITLE
Not recognizing new projects

### ISSUE THREAD

**Issue by ilyador** [bchatard/jetbrains-alfred-workflow#5]
WS 2016.1, v0.8. All project I added after installing workflow won't appear in the search. All projects in the same folder

**Comment by bchatard** [comment]
Hi,

Which version of OSX?
How did you install WS? (caskroom or downloaded from jetbrains website)

Thanks,

**Comment by ilyador** [comment]
10.11.4
from JetBrains website

**Comment by bchatard** [comment]
did you close WS after creating new projet?

**Comment by ilyador** [comment]
Yes, multiple times

**Comment by bchatard** [comment]
can you take a look on this file `~/Library/Preferences/WebStorm2016.1/options/recentProjectDirectories.xml`, and check if you see your new project (path)

**Comment by ilyador** [comment]
Yes, the new projects are there

**Comment by bchatard** [comment]
Please install version available on branch [issue_5](https://github.com/bchatard/jetbrains-alfred-workflow/blob/issue_5/package/JetBrains%20-%20Open%20project.alfredworkflow)

Search the term `log`, you will see a path to a log file. Please provide me this log file.

**Comment by ilyador** [comment]
How can I send it to you privately?

**Comment by bchatard** [comment]
ok, your cli reference old preferences: `~/Library/Preferences/WebStorm11`

please upgrade your cli: https://github.com/bchatard/jetbrains-alfred-workflow#requirements

**Comment by ilyador** [comment]
Works, thanx
