### ISSUE TITLE
PhpStorm 2019.1 breaks the workflow - 'Can't find application path'

### ISSUE THREAD

**Issue by jornetsimon** [bchatard/jetbrains-alfred-workflow#50]
Q | A
--- | ---
Workflow version | _2.0.0_
OSX Version | _10.14.4_
Alfred Version | _3_
JetBrains Product/Version | _PhpStorm / 2019.1_
Installation type | _JB Toolbox_

### Description
Everything worked fined, until the upgrade to PhpStorm 2019.1.
In this version the 'Create command-line launcher' is gone, so the config lives in JB Toolbox.
The _pstorm_ alias is working.

But the workflow fails:
> Can't find application path for '/usr/local/bin/pstorm'

Here is my conf:
<img width="1118" alt="Screenshot 2019-03-29 at 07 49 14" src="https://user-images.githubusercontent.com/936101/55215450-24a55680-51fa-11e9-802e-181c68111fdf.png">

Tried with default _phpstorm_ launcher as well.

**Comment by bchatard** [comment]
Hi @jornetsimon,

Thanks for your issue. Yes it's a known issue (see #48). I will try some workaround as soon as possible.

The _bin_ behaviour is not the same with the 2019.1 JetBrains products.

**Comment by bchatard** [comment]
@jornetsimon please look this new workflow: https://github.com/bchatard/alfred-jetbrains

**Comment by jornetsimon** [comment]
> @jornetsimon please look this new workflow: https://github.com/bchatard/alfred-jetbrains

Yep, this one works fine 😃

**Comment by bchatard** [comment]
@jornetsimon thanks for your feedback. I close this issue. Do not hesitate to open new issue on the other project
