### ISSUE TITLE
Support Android Studio

### ISSUE THREAD

**Issue by tomorrowkey** [bchatard/jetbrains-alfred-workflow#7]
| Q | A |
| --- | --- |
| Workflow version | v0.8 |
| OSX Version | 10.11.05 |
| Alfred Version | 3 |
| JetBrains Product/Version | Android Studio / 2.1.2 |
| Installation type | classic .dmg |
### Description

I add a script filter by myself to support Android Studio like following.

<img src="https://cloud.githubusercontent.com/assets/126019/16789747/1ad176a4-48eb-11e6-84f7-811f610ae2d4.png" width="300" />

Please support Android Studio by default 🙏

**Comment by bchatard** [comment]
ok, I will add Android Studio asap. Thanks for this feedback

**Comment by bchatard** [comment]
@tomorrowkey I add Android Studio support on branch `issue_7`. Can you try workflow on this branch, and let me know if it's ok for you? Thanks

**Comment by tomorrowkey** [comment]
Thank you for quick work 👯 

`JetBrains - Open project.alfredworkflow` is works fine 😄  But `JetBrains - Open project - Alfred2.alfredworkflow` is not include the Android Studio script filter 😭 

Also it is better if update README at `Default keywords` and `Supported Versions` 😉

**Comment by bchatard** [comment]
@tomorrowkey Yes `JetBrains - Open project - Alfred2.alfredworkflow` is a backup for Alfred2 (just in case)
I will update the README, thanks

**Comment by bchatard** [comment]
@tomorrowkey merged, thanks again

**Comment by tomorrowkey** [comment]
> Yes JetBrains - Open project - Alfred2.alfredworkflow is a backup for Alfred2 (just in case)

I see.
Thank you for changing :heart:
